### ISSUE TITLE
Update Nuget package for SpecFlow 2.2.0

### ISSUE THREAD

**Issue by osmanium** [phatcher/SpecFlow.Unity#3]
Current Specflow.Unity is not compatible with Specflow 2.2.0, and when trying to use it with that version throws below exception

> _Message: OneTimeSetUp: System.TypeLoadException : Could not load type 'TechTalk.SpecFlow.Infrastructure.IBindingInstanceResolver' from assembly 'TechTalk.SpecFlow, Version=2.2.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41'._

Will there be any upgrade in the library to support new version?

**Comment by phatcher** [comment]
I'll do a new version shortly

**Comment by victorsantoss** [comment]
That's done over my PR.

#4 Modifications to support Specflow 2.2

**Comment by AlexanderFar** [comment]
Guys, please do it already.

**Comment by victorsantoss** [comment]
For the moment you can use directly from my branch :)

**Comment by aryanreddy** [comment]
Hi victorsantoss
we are also getting same error IBindingInstanceResolver. Can you please let us know what is the fix for this issue.

Thanks & Regards,
Dharma Reddy B.

**Comment by victorsantoss** [comment]
Hey Dharma,

I saw that my pull request (#4 ) was merged some weeks ago, it depends on @phatcher doing a new release over the nuget package.

After that everything will works great.

**Comment by aryanreddy** [comment]
Hi
Thanks for the reply. Can you please let us know what are the changes do we
need to do.

Currently installed specflow version is 2.2.0

Do we need to do any code changes. If what are the changes?


Thanks
Dharma

**Comment by ghost** [comment]
Whats the ETA on this release?

**Comment by phatcher** [comment]
Sorry for the delay, new version published to NuGet
